### ISSUE TITLE
use git sha for version in the Makefile

### ISSUE THREAD

**Issue by arschles** [deis/dockerbuilder#11]
[this line](https://github.com/deis/dockerbuilder/blob/master/Makefile#L12) should change to `VERSION ?= git-$(shell git rev-parse --short HEAD)`

**Comment by technosophos** [comment]
Bumping this to RC1

**Comment by arschles** [comment]
Looks like this was fixed by https://github.com/deis/dockerbuilder/pull/33. Closing
