### ISSUE TITLE
support SOURCE_VERSION

### ISSUE THREAD

**Issue by tmc** [deis/dockerbuilder#125]
ala https://devcenter.heroku.com/changelog-items/630

**Comment by bacongobbler** [comment]
this should be [present in the environment](https://github.com/deis/controller/blob/0e117b1bd04dfd84a94d5e295c4d16328db7e66e/rootfs/api/models/app.py#L852-L853) at runtime. If you want it available during build-time, you'll need to opt into docker's build arguments via `deis config:set DEIS_DOCKER_BUILD_ARGS_ENABLED=true`.
