### ISSUE TITLE
change the 'name' field in the manifest

### ISSUE THREAD

**Issue by arschles** [deis/dockerbuilder#13]
[this line](https://github.com/deis/dockerbuilder/blob/master/manifests/deis-dockerbuilder.yaml#L4) should have `deis-dockerbuilder` as its value

**Comment by smothiki** [comment]
that line is the POD name that we set which is deis-dockerbuilder-appname-gitsha

**Comment by arschles** [comment]
Yup, but builder creates its own manifest and sets the name to that value [here](https://github.com/deis/builder/blob/master/pkg/gitreceive/k8s_util.go#L42).

In fact, I'm guessing this manifest is never used. Is that correct?

**Comment by technosophos** [comment]
Status on this? I can't tell if this is cleanup or a bug for Beta1.
