### ISSUE TITLE
Expose DEBUG env variable for for Kubernetes manifests

### ISSUE THREAD

**Issue by sgoings** [deis/dockerbuilder#23]
As a user of dockerbuilder, I'd like to be able to configure the DEBUG level (currently: true vs. false) via a Kubernetes manifest pod ENV variable. See how Builder allows this behavior:

https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-builder-rc.yaml#L35

**Comment by helgi** [comment]
Looks like this got fixed a long time ago https://github.com/deis/dockerbuilder/commit/82ec3f6981a9832ecf001524ada4cdd6a381cd64 - @bacongobbler can you confirm and close?

**Comment by bacongobbler** [comment]
Indeed. `deis config:set DEIS_DEBUG=1` shows the debug output of dockerbuilder.
