### ISSUE TITLE
add to CI

### ISSUE THREAD

**Issue by arschles** [deis/dockerbuilder#4]
just as [other](https://github.com/deis/workflow) [repos](https://github.com/deis/router) do, travis.ci needs to build this codebase. since the build needs to push to dockerhub and quay.io, this issue implicitly will require a makefile refactor. see https://github.com/deis/minio/pull/9/files#r46733280 for more

**Comment by arschles** [comment]
@smothiki is this fixed by #9?

**Comment by smothiki** [comment]
Nope. But this fixes https://github.com/deis/dockerbuilder/pull/10

**Comment by arschles** [comment]
ok, can you comment there so this issue is auto-closed

**Comment by arschles** [comment]
closing, this component is now in [CI](https://travis-ci.org/deis/dockerbuilder)
