### ISSUE TITLE
Use deis-objectstorage-secret.yaml to get S3 credentials

### ISSUE THREAD

**Issue by arschles** [deis/dockerbuilder#40]

**Comment by arschles** [comment]
[Object storage docs](https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#credentials) should also be upgraded when this work is done.

**Comment by bacongobbler** [comment]
we are [doing so](https://github.com/deis/dockerbuilder/blob/master/rootfs/deploy.py#L41) now. Closing!

**Comment by bacongobbler** [comment]
actually the object storage docs have not been updated. Re-opening.
