### ISSUE TITLE
Docker-py doesn't support insecure registries anymore

### ISSUE THREAD

**Issue by evgenius** [deis/dockerbuilder#44]
docker-py==1.7.0 doesn't support insecure registries.
There's a deprecation message when `client.push()` is called with `insecure_registry=True`: 
https://github.com/docker/docker-py/blob/1.7.0/docker/api/image.py#L209

It tries to connect via HTTPS so https://github.com/deis/helloworld can't be built:

> pushing to registry
> remote: ":"The push refers to a repository [10.254.211.95:80/deis-helloworld](len: 1)"}
> 
> {"errorDetail":{"message":"unable to ping registry endpoint https://10.254.211.95:80/v0/\nv2 ping attempt failed with error: Get https://10.254.211.95:80/v2/: tls: oversized record received with length 20527\n v1 ping attempt failed with error: Get https://10.254.211.95:80/v1/_ping: tls: oversized record received with length 20527"},"error":"unable to ping registry endpoint https://10.254.211.95:80/v0/\nv2 ping attempt failed with error: Get https://10.254remote: 80/v2/: tls: oversized record received with length 20527\n v1 ping attempt failed with error: Get https://10.254.211.95:80/v1/_ping: tls: oversized record received with length 20527"}

**Comment by bacongobbler** [comment]
The reason why they deprecated that flag is because they expect the daemon to handle the --insecure-registry flag instead of the client, which makes sense.

**Comment by evgenius** [comment]
@bacongobbler Does it mean that in order to make Deis registry work in Kubernetes, the whole range of Kubernetes IP addresses should be added to "--insecure-registry" parameter of Docker daemons on all Kubernetes nodes?

**Comment by bacongobbler** [comment]
yep! I do believe we point that out in the v2 documentation.

EDIT: [here](http://docs-v2.readthedocs.org/en/latest/installing-workflow/system-requirements/#docker-insecure-registry)

**Comment by evgenius** [comment]
@bacongobbler Yeah, you do: http://docs-v2.readthedocs.org/en/latest/installing-workflow/system-requirements/#docker-insecure-registry
Sorry I missed that.
