### ISSUE TITLE
Error pushing Dockerfile with workflow-beta4

### ISSUE THREAD

**Issue by chicagozer** [deis/dockerbuilder#60]
Pushing a simple Dockerfile, I'm getting the error below.

`Pushing to registry
{"errorDetail":{"message":"unable to ping registry endpoint https://10.0.250.51:80/v0/\nv2 ping attempt failed with error: Get https://10.0.250.51:80/v2/: tls: oversized record received with length 20527\n v1 ping attempt failed with error: Get https://10.0.250.51:80/v1/_ping: tls: oversized record received with length 20527"},"error":"unable to ping registry endpoint https://10.0.250.51:80/v0/\nv2 ping attempt failed with error: Get https://10.0.250.51:80/v2/: tls: oversized record received with length 20527\n v1 pingremote:  failed with error: Get https://10.0.250.51:80/v1/_ping: tls: oversized record received with length 20527"}
remote: 2016/05/15 05:51:55 Error running git receive hook [Build pod exited with code 1, stopping build.]`

My env variables seem reasonable.

`declare -x DEIS_REGISTRY_SERVICE_HOST="10.0.250.51"
declare -x DEIS_REGISTRY_SERVICE_PORT="80"
declare -x DEIS_REGISTRY_SERVICE_PORT_HTTP="80"`

Is docker-py incorrectly prepending https:// ? 

`print("Pushing to registry")
118 stream = client.push(registry+'/'+imageName, tag=imageTag, stream=True, insecure_registry=True)`

**Comment by kmala** [comment]
did you set insecure registry while creating cluster?
http://docs-v2.readthedocs.io/en/latest/installing-workflow/system-requirements/#docker-insecure-registry

**Comment by chicagozer** [comment]
No :( that was the fix! thank you!

export KUBE_ENABLE_INSECURE_REGISTRY=true
