### ISSUE TITLE
Error pushing from dockerbuilder to registry

### ISSUE THREAD

**Issue by odacremolbap** [deis/dockerbuilder#79]
Hi everyone!

**SO:** CoreOS
**Deis:** 2.1.0
**Kubernetes:** 1.2.4
**Testing App:** helloworld example from Deis

I'm facing an issue with Deis 2.1.0 and Dockerbuilds. The message I get from the dockerbuild pod when executing the example helloworld is:

```
Successfully built b61d0cb0c964
Pushing to registry
    data = reader.read(1)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 320, in read
    flush_decoder = True
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 233, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```

I've seen this same message in Deis and Docker issues, but none of the solutions I've read have worked so far.
#60

Docker daemon includes: `... --insecure-registry=10.0.0.0/8 --selinux-enabled=false ...`

The first thing that doesn't seem right in my nodes is that there are a couple of envs for the registry service:

```
DEIS_REGISTRY_SERVICE_HOST=10.200.162.204
DEIS_REGISTRY_SERVICE_PORT=80
```

and `deploy.py` should be using those

```
registry = os.getenv("DEIS_REGISTRY_SERVICE_HOST") + ":" + os.getenv("DEIS_REGISTRY_SERVICE_PORT")
```

but the error says `(host='localhost', port=None): Read timed out.`

**Comment by bacongobbler** [comment]
this looks very similar to what @dtomcej was seeing, which is https://github.com/docker/docker-py/issues/931.

Also related was https://github.com/deis/deis/issues/5051 though no resolution came out of that.

**Comment by ntfrnzn** [comment]
With new components, kubernetes 1.3.5 & deis 2.3, this same test (helloworld example) fails to push to the deis-registry with a different error, 

> ...
> Successfully built 32dc77ba5fea
> Pushing to registry
> {"errorDetail":{"message":"dial tcp 10.200.169.61:9000: i/o timeout"},"error":"dial tcp 10.200.169.61:9000: i/o timeout"}

That ip:port is the service ip:port of the kubernetes minio service, but the service is certainly accessible.  There's not much information in any of the pod or container logs that I've found to indicate which component is timing out.  Suggestions welcome, of course.

**Comment by kmala** [comment]
@ntfrnzn is the error consistent? what does `kubectl exec -it deis-registry-<> curl http://10.200.169.61:9000 --namespace=deis` say?

**Comment by ntfrnzn** [comment]
I'll bring up another system so I can give a definite answer.  As I recall, curl'ing that service endpoint from a pod in the cluster returned some xml-fragment immediately.

**Comment by ntfrnzn** [comment]
With a newly rebuilt cluster, a slighly different error, 

> Pushing to registry
> Build complete.
> Launching App...
> ...
> 
> ...
> remote: 2016/08/12 21:59:01 Error running git receive hook [publishing release (Unexpected error occurred: error pulling image configuration: Get http://10.200.197.237:9000/registry/docker/registry/v2/blobs/sha256/c7/c7409ac4eb7d2337122889ecaf5df1ee51939ac78b531837cde3d0abbba03577/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=redacted%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160812T215831Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=a8dbd3a49073e88b138917a96fdb902d6c5ae36779a91a6db5a15eb157801a38: dial tcp 10.200.197.237:9000: i/o timeout)]
> To ssh://git@deis-builder.52.34.74.133.nip.io:31820/luxury-utensils.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'ssh://git@deis-builder.52.34.74.133.nip.io:31820/luxury-utensils.git'

curl to the minio service endpoint returns 403 Forbidden, "<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error" 

curl reponse seems expected

**Comment by Joshua-Anderson** [comment]
I quickly edited the URL you posted because it looks like it had part of your aws credentials in it.

**Comment by odacremolbap** [comment]
**Deis** 2.3
**Kubernetes** 1.3.5

I launched a new `Dockerbuild`pod based on a failed one, with an infinite loop. Inside that pod I executed the followind tests:
- After setting `DEIS_DEBUG`I can see that pushing the image is retrying over and over for all layers.
- I installed docker client 1.11, with the same result,  so it doesn't seem to be a network bandwidth issue.
- Minio receives data, there is data in all layers I'm pushing, but can't tell if there is something missing there.
- Installing Minio client and sending huge files to Minio works blazingly fast.

This is the error without debug

```
# python deploy.py 
Step 1 : FROM debian:jessie
---> 1b01529cc499
Step 2 : RUN apt-get update && apt-get install -qy curl
---> Using cache
---> dddfa3e2d5c6
Step 3 : RUN curl -s https://storage.googleapis.com/golang/go1.2.2.linux-amd64.tar.gz | tar -C /usr/local -xz
---> Using cache
---> 534cda9a04e8
Step 4 : ENV GOPATH /go
---> Using cache
---> 0242622bf84e
Step 5 : ENV GOROOT /usr/local/go
---> Using cache
---> 77c863f75945
Step 6 : ENV PATH $PATH:/usr/local/go/bin:/go/bin
---> Using cache
---> a455cb280196
Step 7 : ADD . /go/src/github.com/deis/helloworld
---> Using cache
---> 8478d7dea27a
Step 8 : RUN cd /go/src/github.com/deis/helloworld && go install -v .
---> Using cache
---> 14a66687be6c
Step 9 : EXPOSE 80
---> Using cache
---> 9ee48eea9845
Step 10 : ENTRYPOINT /go/bin/helloworld
---> Using cache
---> b2241163f3df
Successfully built b2241163f3df
Pushing to registry
{"errorDetail":{"message":"dial tcp 10.200.83.220:9000: i/o timeout"},"error":"dial tcp 10.200.83.220:9000: i/o timeout"}
```

This is the last part of the output of a deploy with `DEIS_DEBUG`

![anim](https://cloud.githubusercontent.com/assets/9891289/17733771/811b350a-6478-11e6-84bf-316a4de9a4d7.gif)

And this is a extract of that output, 1/20 messages aprox is a retry message.

```
{"status":"Pushing","progressDetail":{"current":176198144,"total":217789534},"progress":"[========================================\u003e          ] 176.2 MB/217.8 MB","id":"5e84126061c3"}

{"status":"Retrying in 1 second","progressDetail":{},"id":"c862142b51f3"}

...

{"status":"Pushing","progressDetail":{"current":214210728,"total":217789534},"progress":"[=================================================\u003e ] 214.2 MB/217.8 MB","id":"5e84126061c3"}

{"status":"Retrying in 10 seconds","progressDetail":{},"id":"2f71b45e4e25"}

...

{"status":"Pushing","progressDetail":{"current":221405184,"total":217789534},"progress":"[==================================================\u003e] 221.4 MB","id":"5e84126061c3"}

{"status":"Retrying in 9 seconds","progressDetail":{},"id":"2f71b45e4e25"}
```

Executing native docker client output require several shell-shots:

**Beginning**

```
# ./docker push localhost:5555/iamarock
The push refers to a repository [localhost:5555/iamarock]
d8c1631c6365: Pushing 7.035 MB
6f1ab8f6dfd3: Pushing 8.192 kB
5e84126061c3: Pushing 22.23 MB/217.8 MB
c862142b51f3: Pushing 18.69 MB/26.75 MB
2f71b45e4e25: Pushing 10.25 MB/125.1 MB
```

**Pushes OK, but still on pushing state**

```
# ./docker push localhost:5555/iamarock
The push refers to a repository [localhost:5555/iamarock]
d8c1631c6365: Pushing 7.035 MB
6f1ab8f6dfd3: Pushing 8.192 kB
5e84126061c3: Pushing 221.4 MB
c862142b51f3: Pushing 27.58 MB
2f71b45e4e25: Pushing   131 MB
```

**Retries**

```
# ./docker push localhost:5555/iamarock
The push refers to a repository [localhost:5555/iamarock]
d8c1631c6365: Retrying in 16 seconds 
6f1ab8f6dfd3: Retrying in 8 seconds 
5e84126061c3: Pushing 221.4 MB
c862142b51f3: Pushing 27.58 MB
2f71b45e4e25: Pushing 64.52 MB/125.1 MB
```

**Failure**

```
# ./docker push localhost:5555/iamarock
The push refers to a repository [localhost:5555/iamarock]
d8c1631c6365: Pushing 7.035 MB
6f1ab8f6dfd3: Pushing 8.192 kB
5e84126061c3: Pushing 206.8 MB/217.8 MB
c862142b51f3: Pushing 27.58 MB
2f71b45e4e25: Retrying in 13 seconds 
dial tcp 10.200.83.220:9000: i/o timeout
```

I would discard docker-py, as it's not being used by native docker client.
Is there some token from the `deis-registry` that may be getting invalidated?

**Comment by odacremolbap** [comment]
We solved this issue after addin and extra iptables entry to our nodes.

I haven't checked it, but probably some Deis components (registry) are using host network, or being called from the host. We were hitting a race on `iptables` creation between kube-proxy and flannel.

https://github.com/kubernetes/kubernetes/issues/20391

**Comment by Joshua-Anderson** [comment]
Nice sleuthing! I belive the dockerbuilder does push to the deis-reigstry-proxy running on localhost, so an iptables race would explain this.
