### ISSUE TITLE
Needs python linting

### ISSUE THREAD

**Issue by mboersma** [deis/dockerbuilder#8]
Since #6 introduces some python code, we should `flake8` source files in CI as we do in deis/workflow.

**Comment by bacongobbler** [comment]
related to #87

**Comment by bacongobbler** [comment]
also related to #36

**Comment by helgi** [comment]
See deis/controller and how we do `dev_requirements.txt`, how the `Makefile` looks like for that (make test and co) and how that interacts in Travis and friends
