### ISSUE TITLE
Improve testing for dockerbuilder

### ISSUE THREAD

**Issue by smothiki** [deis/dockerbuilder#88]
As of now dockerbuilder is a part of full E2E test. But if we look at functionality here dockerbuilder only does two things in DEIS. Takes a tar file extracts the code, builds a docker container according to the Dockerfile and pushes the container to registry.
Any PR in dockerbuilder should or also do this test instead of running entire E2E suite.

refer deis/workflow-e2e#303

**Comment by bacongobbler** [comment]
related #36

**Comment by bacongobbler** [comment]
closing as a duplicate of #36.
